New coords handler updated to use xyz coordinates
davidecrc/neuroinfer_brainhack23 pull request #15
Opened 2024-05-02 16:29 UTC by saramazz

The functions `run_bayesian_analysis_router`, `area`, and `coordinates` have been modified to utilize `dt_papers_nq` and `xyz_coords`, which are calculated by the `load_or_calculate_variables` function from the `data-neurosynth_version-7_coordinates.tsv` file and affine matrices. In the case of `area`, it is `mask, affine = generate_nifit_mask(area, atlas_path)`.

For `coordinates`, it is `mask, affine = generate_nifit_mask(1, atlas_path)`. 

The time taken to obtain the results has been significantly reduced.

2024-05-02 16:34 UTC, mlionello commented on neuroinfer/code/BayesianAnalysis.py
> +        #results=run_bayesian_analysis_area(cog_list, prior_list, area, radius, result_df, cm)
```suggestion
```

2024-05-02 16:34 UTC, mlionello commented on neuroinfer/code/BayesianAnalysis.py
> +        #dt_papers_nq = pd.read_csv(os.path.join(data_path, 'data-neurosynth_version-7_coordinates.tsv'), sep='\t')
```suggestion
        #dt_papers_nq = pd.read_csv(os.path.join(data_path, 'data-neurosynth_version-7_coordinates.tsv'), sep='\t')
```

2024-05-02 16:36 UTC, mlionello commented on neuroinfer/code/BayesianAnalysis.py
> +    #affine_inv = np.linalg.inv(mask_nifti.affine) #inverse of the affine matrix to convert from MNI coordinates tp voxel coordinates
```suggestion
```

2024-05-02 16:37 UTC, mlionello requested changes
remove comments

2024-05-02 16:49 UTC, mlionello approved these changes

2024-05-04 07:52 UTC, davidecrc approved these changes

2024-05-04 08:12 UTC, merged