padding inserted into run_bayesian_analysis_area
davidecrc/neuroinfer_brainhack23 pull request #20
Opened 2024-07-04 13:46 UTC by saramazz

**Description:**
Enhanced `run_bayesian_analysis_area` to incorporate padding functionality for efficient spatial analysis.
Correct the error in the calling of run_bayesian_analysis_area, feature_df was missing. Rename of the saved result folder as RESULTS_FOLDER.

1. **Padding Implementation:**
   - Introduced padding functionality to optimize spatial computations within specified radius.
   - Added `padding` calculation based on one-third of the original `radius`.

2. **Coordinate Management:**
   - Implemented `visited_coord` array to track visited coordinates with padding.
   - Utilized `update_visited_coord` function to manage coordinate visits with padding adjustments.

3. **Error Handling:**
   - Integrated boundary checks in `is_visited` to prevent out-of-bounds errors.
   - Ensured normalized coordinates (`x_norm`, `y_norm`, `z_norm`) remain within array bounds.

4. **Progress Tracking:**
   - Implemented progress logging and temporary file management for iterative computations.

5. **Functionality Validation:**
   - Verified functionality through distance checks and iterative processing updates.

**Functions Introduced:**
- `update_visited_coord`: Manages the update of visited coordinates with padding.
- `is_visited`: Checks if a coordinate has been visited while ensuring array bounds are respected.
- `normalize_coord`: Normalizes target coordinates relative to specified ranges for consistent processing.

2024-07-12 16:35 UTC, mlionello requested changes
spotted some possible bugs :)

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
> +            center = np.array([x_target, y_target, z_target])
```suggestion
            center = np.array([x_target, y_target, z_target], dtype=np.float32)
```

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
> +        sort_column = "Ratio"
```suggestion
```

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
> +        sort_column = "Difference"
```suggestion
```

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
> +        sort_column = "Z-measure"
```suggestion
```

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
> +
```suggestion
```

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
> +    # coord=[]
```suggestion
```

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
> +    coord_ranges = {
at this point coordinates_area is a N list of triplets. coordinates_area[0] contains the first triplets of coordinates

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
> +    coord_ranges = {
we might want something like:
"xmax" : max([a[0] for a in coordinates_area]),

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
> +    ):  # -1 in order to have the last coordinates_area[i+1]) #TODO remove this -1
can we already safely get rid of -1?

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
>          if i == 0:
do we still need a special case for the first iteration?

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
> +            if not is_visited((x_norm, y_norm, z_norm), visited_coord):
in order to avoid nested code we can simply put it 'if is visited: continue;'

2024-07-12 16:35 UTC, mlionello commented on neuroinfer/code/run_bayesian.py
> +    visited_coords[x_min:x_max, y_min:y_max, z_min:z_max] = 1
this will occupy a cubic space of 1s. in order to have it spheric we can recycle  np.linalg.norm

2024-10-31 19:40 UTC, mlionello approved these changes

2024-11-22 15:32 UTC, davidecrc approved these changes

2024-11-22 15:32 UTC, merged